services:
  - type: web
    name: shop-cart-django
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
      - key: PYTHON_VERSION
        value: 3.9
      - key: SECRET_KEY
        value: {{ADD_YOUR_SECRET_KEY_HERE}}
      - key: MERCHANT_KEY
        value: {{ADD_YOUR_PAYTM_MERCHANT_KEY_HERE}}
      - key: MID
        value: {{YOUR_PAYTM_MID}}
