services:
  - type: web
    name: shop-cart-django
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: MID
        value: your-paytm-mid
      - key: MERCHANT_KEY
        value: your-paytm-merchant-key
