services:
  - type: web
    name: shop-cart-django
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      DJANGO_SETTINGS_MODULE:env.DJANGOSETTNGSKEY,
      PYTHON_VERSION:env.PYTHONVERSIONKEY
